### PR TITLE
NSMicrophoneUsageDescription and clear embed stdlib

### PR DESCRIPTION
**Pull request by evermeer**
- Do not use Always embed swift standard libraries
- NSMicrophoneUsageDescription in info.plist

### CODE REVIEW

**Comment by evermeer** [comment]
Hmm... Did it again... Should have been 2 pull requests...

There is 1 issue with the general structure...(not Bluetooth specific) When enabeling or disabeling bluetooth you will see it happening in the output window, but the tablecell is not automatically reloaded.

**Comment by evermeer** [comment]
Ok... I also added ArekMotion now...
I had to use UserDefaults to see if this never has been asked for.

**Comment by ennioma** [comment]
Hi @evermeer,
I've raised the PR #71 that contains

- Core Bluetooth
- Core Motion
- demo projects fixes
- dump version to 1.0.0

I'll do a couple more tests before merging it to master and release arek 1.0.0

If you have time, I'd like to have your feedback on this PR :)

**Comment by evermeer** [comment]
PR #71 looks good. 

There is one thing that I noticed. In the switch case you have this code:

```
        if let completion = self.completion {
                 return completion(.Denied)
        }
         break
```
But it's a function without return value, so why do you call `return completion(.Denied)`
It looks like the completion should be something to return, but it will return nothing.
And since you would just fall through the switch you could leave out the return at all. So you could just call `completion(.Denied)`. And that together with the if would be the same as: `completion?(.Denied)`. So no if let is needed. So the final code would be:

```
         completion?(.Denied)
         break
```

**Pull request merged**
