### PR TITLE
Updated to Swift 4

### PR DESCRIPTION
**Pull request by mouhcine**
A few notes:
- I'm still not using the library, but I see that it's not very compatible with Objective C, so I avoided adding `@objc` and `@objcmembers` to the API
- I updated `Cartfile` and `Cartfile.resolved` without testing it
- Let me know if you prefer to use 2.0 as a version number instead

### CODE REVIEW

**Comment by ennioma** [comment]
Thanks for the contribution mate!

So, yes I already reverted an old PR that was opened to update the project to swift 4 because I want to change the version number to `2.0`. So the versions `1.x.y` will refer to swift 3 for a while.

**Comment by mouhcine** [comment]
Thank _you_ for the library!

I don't understand from your comment if you want me to change the version to 2.0.0 or if you prefer to wait to be able to add other things?

**Comment by ennioma** [comment]
Oh sorry, yes please update it to the `2.0.0`!

**Comment by mouhcine** [comment]
Done! :)

**Pull request merged**
