### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by evermeer**
- public to open
- no self.permission = self (memory leak)
- NSLog to print ✅
- init with default parameters ✅
- code moved to base with reference to protocol ✅
- fix ArekContacts

added ArekSpeachRecognizer and ArekReminders

### CODE REVIEW

**Comment by ennioma** [comment]
This branch is too big and now it contains conflicts.

Thanks for your brilliant job @evermeer, I'll proceed analyzing the PR and merging a change at time.

**Comment by evermeer** [comment]
Have fun 😃 
I know I'm having fun!

**Comment by ennioma** [comment]
This is good @evermeer :)

**Comment by evermeer** [comment]
OK, i'm ready for today... Bluetooth and Motion are not as easy as the others... Maybe I have some time for these later this week...

**Comment by ennioma** [comment]
It sounds good to me,
Thanks for your effort!

Maybe I'll perform a big refactor also during Xmas holidays 😊

**Comment by ennioma** [comment]
Init methods extended with PR #60

**Comment by ennioma** [comment]
NSLog replaced by print [https://github.com/ennioma/arek/commit/a3758edd4846e6f22c87a081c554f6cedd4dc1d0](a3758ed)

**Comment by ennioma** [comment]
manage() func moved to ArekBasePermission class in #61

**Comment by ennioma** [comment]
@evermeer I'm not so sure about the memory leak,
could you please explain me where have you fixed it and why does it introduce a memory leak?

- ArekReminder was already there (in the Event group). Could you please check?

One way to understand the remaining refactor could be that you rebase (or merge) the current develop in your branch.

**Comment by ennioma** [comment]
Also ArekContacts should have been already fixed or not?

**Comment by evermeer** [comment]
Yeah, sorry, I should have updated my branch. Instead I continued with the CloudKit branch. I will continue with the develop branch in a moment to see what's missing..

About the memory leak...
In every Arek class you where doing this:
`self.permission = self`
Where the permission variable was defined like:
`var permission: ArekPermissionProtocol!`
When you do something like:
`var a = ArekCamera()`
Then there will be immediately a reference count to that ArekCamera object of 1.
But then in the init you call the` self.permissions = self` which will increase the reference count to 2
If you then clear the a variable with something like `a = nil` then the reference count will go back to 1.
Since the reference in ArekCamera is not cleared it will never go down to 0 and the memory will remain.
Of course in this situation it would not be a huge problem. You usually don't create a lot of ArekCamera classes. But still it's a memory leak.
One other way you could solve this is by defining the property weak like this:
`weak var permission: ArekPermissionProtocol!`
But then that exclamation mark at the end is really dangerous because permissions could be nil and you have to test for it always.

That exclamation mark is an other thing. I really don't like using that anywhere.  It's asking for problems. You can even find multiple articles that this default for IBOutlets should be changed (https://blog.curtisherbert.com/to-optional-or-not-to-optional-iboutlet/)  It's also why you had that crash with ArekContacts earlier. So instead you could assign a default value or make it optional with a questionmark.

**Comment by ennioma** [comment]
Yeah thank you for the explanation,
Yesterday I missed the

self.permission = self in any permission class 

Ok this will be the next update

**Comment by evermeer** [comment]
hold on, a fresh PR is comming, you could then cancel this one...

**Comment by ennioma** [comment]
Cool, I close this one

**Pull request closed without merging**
